use_frameworks!

platform :ios, '8.0'

source 'git@github.com:CocoaPods/Specs.git'
source 'git@github.com:Minghao2017/Specs.git'

target 'MHAccountUI_Example' do
  pod 'MHAccountUI', :path => '../'

  target 'MHAccountUI_Tests' do
    inherit! :search_paths

    
  end
end
